services:
  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  catalog-viewer:
    build:
      context: ./catalog-viewer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/games_db?authSource=admin
      - HOSTNAME=0.0.0.0
    depends_on:
      - mongodb

  games-api:
    build:
      context: ./games-api
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/games_db?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo_data:
