# assert env vars exist and if it doesnt fail
#

services:
  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/?authSource=admin
      depends_on:
        - mongodb

  catalog-viewer:
    build:
      context: ./catalog-viewer
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=mongodb://admin:password@mongodb:27017/games_db?authSource=admin
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
    depends_on:
      - mongodb

  games-api:
    build:
      context: ./games-api
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/games_db?authSource=admin
      # put a env in root and then read from env in this file
      - CLIENT_ID=${CLIENT_ID:?IGDB API Client ID needs to be defined in as an environment variable before running}
      - CLIENT_SECRET=${CLIENT_SECRET:?IGDB API Client secret needs to be defined in as an environment variable before running}
    depends_on:
      - mongodb

volumes:
  mongo_data:
