services:
  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/?authSource=admin

  catalog-viewer:
    build:
      context: ./catalog-viewer
      dockerfile: dockerfile
      args:
        - MONGODB_URI=mongodb://admin:password@mongodb:27017/games_db?authSource=admin
    profiles: ["web-dev"]
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: ./catalog-viewer/
          target: /app/
          ignore:
            - node_modules/
            - .next/
            - out/
        - action: rebuild
          path: ./catalog-viewer/dockerfile

  admin-panel:
      build:
        context: ./admin-panel
        dockerfile: dockerfile
        args:
          - MONGODB_URI=mongodb://admin:password@mongodb:27017/games_db?authSource=admin
          - CLIENT_ID=${CLIENT_ID:?IGDB API Client ID needs to be defined in as an environment variable before running}
          - CLIENT_SECRET=${CLIENT_SECRET:?IGDB API Client secret needs to be defined in as an environment variable before running}
      profiles: ["web-dev"]
      ports:
        - "3001:3000"
      depends_on:
        - mongodb
      develop:
        watch:
          - action: sync
            path: ./admin-panel/
            target: /app/
            ignore:
              - node_modules/
              - .next/
              - out/
          - action: rebuild
            path: ./admin-panel/dockerfile

  games-api:
    build:
      context: ./games-api
    profiles : ["games-microservice"]
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/games_db?authSource=admin
      - CLIENT_ID=${CLIENT_ID:?IGDB API Client ID needs to be defined in as an environment variable before running}
      - CLIENT_SECRET=${CLIENT_SECRET:?IGDB API Client secret needs to be defined in as an environment variable before running}

volumes:
  mongo_data:
